services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/code
      - /code/.venv
      - type: volume
        source: transport_data
        target: /code/transport_data
        read_only: false
        # Mounted only in non-test environments
        # Runtime logic in settings.py should switch DB path based on APP_ENV
    ports:
      - "8000:8000"
    environment:
      - SERVICE_DEBUG=true
      - SERVICE_ENVIRONMENT=ci
      - DB_DSN=sqlite+aiosqlite:///./transport_data/transport.db
    command:
      ["uv", "run", "python", "-m", "app"]

volumes:
  transport_data:
